name: Android APK Olusturucu
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: JDK 17 Kur
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Calistirma Yetkisi Ver
        run: chmod +x gradlew

      - name: APK Derle (Debug)
        run: ./gradlew assembleDebug

      - name: APK Dosyasini Yukle
        uses: actions/upload-artifact@v4
        with:
          name: uygulama-dosyasi
          path: app/build/outputs/apk/debug/app-debug.apk
